apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-pipeline-app
  template:
    metadata:
      labels:
        app: cicd-pipeline-app
    spec:
      containers:
        - name: cicd-pipeline-container
          image: daoducan88/test-ci-cd-pipeline:1.0.1.9
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
